name: "Test for Kibot worflow"

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2
      with:
        # Required - kibot config file
        config: test.kibot.yaml

