kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

global:
  # We want the revision added to the names for this project
  output: '%f-%i_%r.%x'

outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .

  - name: 'interactive_bom'
    comment: "Interactive Bill of Materials (HTML)"
    type: ibom
    dir: BoM

  - name: step
    comment: "Generate 3D model (STEP)"
    type: step
    dir: 3D
    options:
      metric_units: true
